apps/roadtrip_web/lib/roadtrip_web/router.ex
defmodule RoadtripWeb.Router do
  use RoadtripWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RoadtripWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RoadtripWeb do
    pipe_through :browser

    get "/", PageController, :index

    # Route to vehicles by their VIN, not by their database ID.
    resources "/vehicles", VehicleController, param: "vin" do
      resources "/log", MeasurementController, param: "moment"

      get "/batch_load", MeasurementController, :batch_upload_form
      post "/batch_load", MeasurementController, :batch_upload
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", RoadtripWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RoadtripWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/roadtrip_web/lib/roadtrip_web/controllers/measurement_controller.ex
defmodule RoadtripWeb.MeasurementController do
  use RoadtripWeb, :controller

  alias Roadtrip.{Garage, Garage.Measurement, Repo}

  def index(conn, %{"vehicle_vin" => vin}) do
    vehicle = vin |> Garage.get_vehicle_by_vin!()
    measurements = vehicle |> Garage.list_measurements()
    conn |> render("index.html", measurements: measurements, vehicle: vehicle)
  end

  def new(conn, %{"vehicle_vin" => vin}) do
    vehicle = vin |> Garage.get_vehicle_by_vin!()
    changeset = Garage.change_measurement(%Measurement{})
    conn |> render("new.html", changeset: changeset, vehicle: vehicle)
  end

  def create(conn, %{"vehicle_vin" => vin, "measurement" => measurement_params}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)

    case Garage.create_measurement(vehicle, measurement_params) do
      {:ok, measurement} ->
        conn
        |> put_flash(:info, "Measurement created successfully.")
        |> redirect(to: Routes.vehicle_measurement_path(conn, :show, vehicle, measurement))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn |> render("new.html", changeset: changeset, vehicle: vehicle)
    end
  end

  def show(conn, %{"vehicle_vin" => vin, "moment" => moment}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)

    measurement =
      Garage.get_measurement!(vehicle, moment |> from_param()) |> Repo.preload(:vehicle)

    conn |> render("show.html", measurement: measurement, vehicle: measurement.vehicle)
  end

  def edit(conn, %{"vehicle_vin" => vin, "moment" => moment}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)

    measurement =
      Garage.get_measurement!(vehicle, moment |> from_param()) |> Repo.preload(:vehicle)

    changeset = Garage.change_measurement(measurement)

    conn
    |> render("edit.html",
      measurement: measurement,
      changeset: changeset,
      vehicle: measurement.vehicle
    )
  end

  def update(conn, %{
        "vehicle_vin" => vin,
        "moment" => moment,
        "measurement" => measurement_params
      }) do
    vehicle = Garage.get_vehicle_by_vin!(vin)
    measurement = Garage.get_measurement!(vehicle, moment |> from_param())

    case Garage.update_measurement(measurement, measurement_params) do
      {:ok, measurement} ->
        conn
        |> put_flash(:info, "Measurement updated successfully.")
        |> redirect(to: Routes.vehicle_measurement_path(conn, :show, vehicle, measurement))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> render("edit.html", measurement: measurement, changeset: changeset, vehicle: vehicle)
    end
  end

  def delete(conn, %{"vehicle_vin" => vin, "moment" => moment}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)
    measurement = Garage.get_measurement!(vehicle, moment |> from_param())
    {:ok, _measurement} = Garage.delete_measurement(measurement)

    conn
    |> put_flash(:info, "Measurement deleted successfully.")
    |> redirect(to: Routes.vehicle_measurement_path(conn, :index, vehicle))
  end

  @doc """
  Renders the page to upload a batch collection of odometer measurements.
  """
  def batch_upload_form(conn, %{"vehicle_vin" => vin}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)
    conn |> render("batch.html", vehicle: vehicle)
  end

  @doc """
  Processes a CSV batch of `Measurement` records.

  Duplicate this function with other `content_type:` values for other filetypes.

  ## CSV Format

  See `Measurement.parse_csv_row/1`.
  """
  def batch_upload(
        conn,
        %{
          "vehicle_vin" => vin,
          "upload" => %{
            "file" => %Plug.Upload{path: path, content_type: "text/csv"}
          }
        }
      ) do
    vehicle = Garage.get_vehicle_by_vin!(vin)

    path
    |> File.stream!()
    |> CSV.decode(headers: true)
    |> Stream.map(fn {:ok, row} -> row end)
    |> Stream.map(&Measurement.parse_csv_row/1)
    |> Garage.batch_create_measurements(vehicle)

    conn |> redirect(to: Routes.vehicle_measurement_path(conn, :index, vehicle))
  end

  # Since `Phoenix.Param.to_param` replaces `:` with `-`, this turns the param
  # back into a usable `DateTime`.
  @spec from_param(String.t()) :: DateTime.t()
  defp from_param(moment_str) when is_binary(moment_str) do
    re = ~r/^(?<Y>\d{4})-(?<M>\d{2})-(?<D>\d{2})T(?<h>\d{2})-(?<m>\d{2})-(?<s>\d{2})Z$/

    %{"Y" => yr, "M" => mo, "D" => dy, "h" => hr, "m" => mn, "s" => sc} =
      Regex.named_captures(re, moment_str)

    {year, ""} = yr |> Integer.parse()
    {month, ""} = mo |> Integer.parse()
    {day, ""} = dy |> Integer.parse()
    {hour, ""} = hr |> Integer.parse()
    {minute, ""} = mn |> Integer.parse()
    {second, ""} = sc |> Integer.parse()
    date = Date.new!(year, month, day)
    time = Time.new!(hour, minute, second)
    DateTime.new!(date, time)
  end
end

defimpl Phoenix.Param, for: Roadtrip.Garage.Measurement do
  def to_param(%Roadtrip.Garage.Measurement{moment: moment}) do
    moment
    |> DateTime.truncate(:second)
    |> DateTime.to_iso8601(:extended)
    |> String.replace(":", "-")
  end
end

apps/roadtrip_web/lib/roadtrip_web/views/measurement_view.ex
defmodule RoadtripWeb.MeasurementView do
  use RoadtripWeb, :view
end

apps/roadtrip_web/lib/roadtrip_web/templates/measurement/batch.html.heex
<h1>Odometer Bulk Upload</h1>

<h2>For <%= @vehicle |> Roadtrip.Garage.Vehicle.show_name() %></h2>

<p>Upload a CSV file containing existing vehicle-history records here.</p>

<p>The CSV file must have the following columns:</p>

<ul>
  <li>
    <strong>Date</strong>:
    A datetime in the format `YYYY-MM-DD hh:mm`. The parser currently does not
    look for a timezone marker, and interprets them as UTC.
  </li>
  <li>
    <strong>Odometer</strong>:
    An integer. Tenths-of-a-mile (or kilometer) are not currently supported.
  </li>
</ul>

<.form let={f} for={:upload}, multipart>
  <%= label f, :file, "Batch measurement file" %>
  <%= file_input f, :file %>

  <div>
    <%= submit "Upload" %>
  </div>
</.form>

apps/roadtrip_web/lib/roadtrip_web/templates/measurement/edit.html.heex
<h1>Edit Measurement</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.vehicle_measurement_path(@conn, :update, @vehicle, @measurement)) %>

<span><%= link "Back", to: Routes.vehicle_measurement_path(@conn, :index, @vehicle) %></span>

apps/roadtrip_web/lib/roadtrip_web/templates/measurement/form.html.heex
<.form let={f} for={@changeset}, action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :odometer %>
  <%= number_input f, :odometer, inputmode: "decimal", pattern: "[0-9]+(\\.[0-9])?" %>
  <%= error_tag f, :odometer %>

  <%= label f, :moment %>
  <p>
    Use your local time and select your timezone. The server will translate
    accordingly.
  </p>
  <% now = DateTime.utc_now() %>
  <%= datetime_select f, :moment, year: [options: 1954 .. now.year + 1, selected: now.year], month: [selected: now.month], day: [selected: now.day], hour: [selected: now.hour], minute: [selected: now.minute] %>
  <%= error_tag f, :moment %>

  <%= label f, :tz, "Timezone" %>
  <%= RoadtripWeb.tz_select f, :tz, selected: "Etc/UTC" %>
  <%= error_tag f, :tz %>

  <div id="refuel" class="form-group">
    <h2>Refueling</h2>
    <div class="form-group refuel-input">
      <%= label f, :price, "Fuel Price" %>
      <%= number_input f, :price, inputmode: "decimal", pattern: "[0-9]+\\.[0-9]{2}9", step: "0.001" %>
      <%= error_tag f, :price %>
    </div>

    <div class="form-group refuel-input">
      <%= label f, :volume, "Fuel Volume" %>
      <%= number_input f, :volume, inputmode: "decimal", pattern: "[0-9]+\\.[0-9]{3}", step: "0.001" %>
      <%= error_tag f, :volume %>
    </div>

    <div class="form-group noscript">
      <%= label f, :use_refuel, "Submit refuel?", style: "display: inline-block;" %>
      <%= checkbox f, :use_refuel %>
    </div>
  </div>
  <div>
    <%= submit "Save" %>
  </div>
</.form>

<style type="text/css">
  .refuel-input {
    width: calc(50% - 4px);
    display: inline-block;
  }
</style>

apps/roadtrip_web/lib/roadtrip_web/templates/measurement/index.html.heex
<h1>Listing Measurements</h1>

<h2><%= @vehicle |> Roadtrip.Garage.Vehicle.show_name() %></h2>

<table>
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Odometer</th>
      <th>Fuel Volume</th>
      <th>Fuel Cost</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for measurement <- @measurements |> Enum.reverse do %>
      <tr>
        <td><%= measurement |> Roadtrip.Garage.Measurement.show_moment() %></td>
        <td class="text-right"><%= measurement |> Roadtrip.Garage.Measurement.show_odometer() %></td>
        <%= if rf = measurement |> Roadtrip.Garage.Measurement.refuel() do %>
          <td class="text-right">
            <%= rf.volume |> Decimal.round(3) %>
          </td>
          <td class="text-right">
            <%= rf |> Roadtrip.Garage.Refuel.total_cost() |> Number.Currency.number_to_currency(precision: 2) %>
          </td>
        <% else %>
          <td></td><td></td>
        <% end %>

        <td>
          <span><%= link "Show", to: @conn |> Routes.vehicle_measurement_path(:show, @vehicle, measurement) %></span>
          <span><%= link "Edit", to: @conn |> Routes.vehicle_measurement_path(:edit, @vehicle, measurement) %></span>
          <span><%= link "Delete", to: @conn |> Routes.vehicle_measurement_path(:delete, @vehicle, measurement), method: :delete, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <% {vol, cost} = Roadtrip.Garage.refuel_sum(@measurements) %>
      <th>Total Costs</th>
      <th></th>
      <th class="text-right">
        <%= vol |> Decimal.round(3) %>
      </th>
      <th class="text-right">
        <%= cost |> Number.Currency.number_to_currency() %>
      </th>
      <th></th>
    </tr>
  </tfoot>
</table>

<span><%= link "New Measurement", to: @conn |> Routes.vehicle_measurement_path(:new, @vehicle) %></span>
| <span><%= link "Upload CSV", to: @conn |> Routes.vehicle_measurement_path(:batch_upload_form, @vehicle) %></span>

<style type="text/css">
.text-right {
  text-align: right;
}
</style>

apps/roadtrip_web/lib/roadtrip_web/templates/measurement/new.html.heex
<h1>New Measurement</h1>

<p>for <%= @vehicle |> Roadtrip.Garage.Vehicle.show_name() %></p>

<%= render "form.html", Map.put(assigns, :action, Routes.vehicle_measurement_path(@conn, :create, @vehicle)) %>

<span><%= link "Back", to: Routes.vehicle_measurement_path(@conn, :index, @vehicle) %></span>

apps/roadtrip_web/lib/roadtrip_web/templates/measurement/show.html.heex
<h1>Show Measurement</h1>

<ul>

  <li>
    <strong>Vehicle:</strong>
    <%= link @vehicle |> Roadtrip.Garage.Vehicle.show_name(), to: Routes.vehicle_path(@conn, :show, @vehicle) %>
  </li>

  <li>
    <strong>Moment:</strong>
    <%= @measurement |> Roadtrip.Garage.Measurement.show_moment() %>
  </li>

  <li>
    <strong>Odometer:</strong>
    <%= @measurement |> Roadtrip.Garage.Measurement.show_odometer() %>
  </li>

  <%= if rf = @measurement |> Roadtrip.Garage.Measurement.refuel() do %>
    <li>
      <strong>Refuel:</strong>
      <%= rf |> Roadtrip.Garage.Refuel.show() %>
    </li>
  <% end %>

</ul>

<span><%= link "Edit", to: @conn |> Routes.vehicle_measurement_path(:edit, @vehicle, @measurement) %></span> |
<span><%= link "Back", to: @conn |> Routes.vehicle_measurement_path(:index, @vehicle) %></span>