apps/roadtrip_web/lib/roadtrip_web/router.ex
defmodule RoadtripWeb.Router do
  use RoadtripWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RoadtripWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RoadtripWeb do
    pipe_through :browser

    get "/", PageController, :index

    # Route to vehicles by their VIN, not by their database ID.
    resources "/vehicles", VehicleController, param: "vin" do
      resources "/log", MeasurementController, param: "moment"

      get "/batch_load", MeasurementController, :batch_upload_form
      post "/batch_load", MeasurementController, :batch_upload
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", RoadtripWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RoadtripWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/roadtrip_web/lib/roadtrip_web/controllers/vehicle_controller.ex
defmodule RoadtripWeb.VehicleController do
  use RoadtripWeb, :controller

  alias Roadtrip.Garage
  alias Roadtrip.Garage.Vehicle

  def index(conn, _params) do
    vehicles = Garage.list_vehicles()
    conn |> render("index.html", vehicles: vehicles)
  end

  def new(conn, _params) do
    changeset = Garage.change_vehicle(%Vehicle{})
    conn |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"vehicle" => vehicle_params}) do
    case Garage.create_vehicle(vehicle_params) do
      {:ok, vehicle} ->
        conn
        |> put_flash(:info, "Vehicle created successfully.")
        |> redirect(to: Routes.vehicle_path(conn, :show, vehicle))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, %{"vin" => vin}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)
    conn |> render("show.html", vehicle: vehicle)
  end

  def edit(conn, %{"vin" => vin}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)
    changeset = Garage.change_vehicle(vehicle)
    conn |> render("edit.html", vehicle: vehicle, changeset: changeset)
  end

  def update(conn, %{"vin" => vin, "vehicle" => vehicle_params}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)

    case Garage.update_vehicle(vehicle, vehicle_params) do
      {:ok, vehicle} ->
        conn
        |> put_flash(:info, "Vehicle updated successfully.")
        |> redirect(to: Routes.vehicle_path(conn, :show, vehicle))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn |> render("edit.html", vehicle: vehicle, changeset: changeset)
    end
  end

  def delete(conn, %{"vin" => vin}) do
    vehicle = Garage.get_vehicle_by_vin!(vin)
    {:ok, _vehicle} = Garage.delete_vehicle(vehicle)

    conn
    |> put_flash(:info, "Vehicle deleted successfully.")
    |> redirect(to: Routes.vehicle_path(conn, :index))
  end
end

# The web API accesses vehicles by VIN, not by database ID.
defimpl Phoenix.Param, for: Roadtrip.Garage.Vehicle do
  def to_param(%Roadtrip.Garage.Vehicle{vin: vin}), do: vin
end

apps/roadtrip_web/lib/roadtrip_web/views/vehicle_view.ex
defmodule RoadtripWeb.VehicleView do
  use RoadtripWeb, :view
end

apps/roadtrip_web/lib/roadtrip_web/templates/vehicle/edit.html.heex
<h1>Edit Vehicle</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.vehicle_path(@conn, :update, @vehicle)) %>

<span><%= link "Back", to: Routes.vehicle_path(@conn, :index) %></span>

apps/roadtrip_web/lib/roadtrip_web/templates/vehicle/form.html.heex
<.form let={f} for={@changeset}, action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <small>(optional)</small>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :make %>
  <%= text_input f, :make %>
  <%= error_tag f, :make %>

  <%= label f, :model %>
  <%= text_input f, :model %>
  <%= error_tag f, :model %>

  <%= label f, :year %>
  <%# `inputmode="numeric"` prompts software keyboards to show a ten-key. %>
  <%= number_input f, :year, inputmode: "numeric", pattern: "\\d*" %>
  <%= error_tag f, :year %>

  <%= label f, :vin, "VIN" %>
  <small>
    North American VINs are 17 alphanumeric digits, except for I, O, and Q. This
    is not case-sensitive.
  </small>
  <%= text_input f, :vin, pattern: Roadtrip.Garage.Vin.html_input_pattern() %>
  <%= error_tag f, :vin %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

apps/roadtrip_web/lib/roadtrip_web/templates/vehicle/index.html.heex
<h1>Listing Vehicles</h1>

<p>
  Vehicles are ordered by name, then by VIN.
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>VIN</th>

      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for vehicle <- @vehicles do %>
      <tr>
        <td><%= link vehicle.name, to: @conn |> Routes.vehicle_path(:show, vehicle) %></td>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.vin %></td>

        <td><%= link "History", to: Routes.vehicle_measurement_path(@conn, :index, vehicle) %></td>
        <td>
          <span><%= link "Edit", to: @conn |> Routes.vehicle_path(:edit, vehicle) %></span>
          <span><%= link "Delete", to: @conn |> Routes.vehicle_path(:delete, vehicle), method: :delete, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= link "New Vehicle", to: @conn |> Routes.vehicle_path(:new) %></span>

apps/roadtrip_web/lib/roadtrip_web/templates/vehicle/new.html.heex
<h1>Register New Vehicle</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.vehicle_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.vehicle_path(@conn, :index) %></span>

apps/roadtrip_web/lib/roadtrip_web/templates/vehicle/show.html.heex
<h1>Show Vehicle</h1>

<ul>

  <%= if @vehicle.name do %>
    <li>
      <strong>Name:</strong>
      <%= @vehicle.name %>
    </li>
  <% end %>

  <li>
    <strong>Make:</strong>
    <%= @vehicle.make %>
  </li>

  <li>
    <strong>Model:</strong>
    <%= @vehicle.model %>
  </li>

  <li>
    <strong>Year:</strong>
    <%= @vehicle.year %>
  </li>

  <li>
    <strong>VIN:</strong>
    <%= @vehicle.vin %>
  </li>

  <li>
    <%= link "History", to: @conn |> Routes.vehicle_measurement_path(:index, @vehicle) %>
  </li>

  <li>
    <%= link "Batch Upload", to: @conn |> Routes.vehicle_measurement_path(:batch_upload_form, @vehicle) %>
  </li>

</ul>

<span><%= link "Edit", to: @conn |> Routes.vehicle_path(:edit, @vehicle) %></span> |
<span><%= link "Back", to: @conn |> Routes.vehicle_path(:index) %></span>